"""added relationship

Revision ID: fefdcd41b112
Revises: cbbb144eb17c
Create Date: 2024-04-07 12:56:52.214083+00:00

"""


# revision identifiers, used by Alembic.
revision = "fefdcd41b112"
down_revision = "cbbb144eb17c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
